### ISSUE TITLE
Create branch of existing content and update to current version

### ISSUE THREAD

**Issue by djccarew** [IBM/cloudpakforintegration-workshop#18]
Working on rewrites to the content for the upcoming AIOps and Integration conference. There are lots of changes (eg Event Streams is no longer part of the product and App Connect has Event driven flows now) but I would like to keep the layout and structure that's here  and reuse what I can) rather than creating a new repo.  I need edit access to the repo to create a branches and update the master branch .

**Comment by stevemar** [comment]
@djccarew you should have access now. thanks for keeping the structure together rather than creating a new repo. 

LMK if you want me to review any PRs
